[package]
name = "erst-shared"
version = "0.2.0"
authors = ["Jacob Brown <kardeiz@gmail.com>"]
edition = "2018"
readme = "../README.md"
license = "MIT"
description = "Embedded Rust"

[dependencies]
pest = "2.1.1"
pest_derive = "2.1.0"